/**
 * Feature Configuration Module
 * Uses custom placeholders for dynamic values
 *
 * Available placeholders:
 * - {{TICKETS}} - Auto-detected tickets
 * - {{SIZE}} - PR size (small/medium/large)
 * - {{IMPACT}} - Impact score
 * - {{CHANGES}} - Summary of changes
 * - {{AUTHOR}} - PR author
 * - {{BRANCH}} - Branch name
 */

export const featureConfig = {
  // Feature flags for enabling/disabling features
  features: {
    ticketDetection: true,
    titleEnhancement: true,
    prSizeWarning: true,
    customPlaceholders: true,
    ghostCommitDetection: false,
    multiLanguageSupport: false,
    breakingChangeDetection: false,
    semanticVersioning: false,
  },

  // Placeholder templates for different sections
  templates: {
    // Header template with author and branch
    header: `## PR Summary
    
**Author:** {{AUTHOR}}  
**Branch:** {{BRANCH}}  
**Size:** {{SIZE}}  
**Impact:** {{IMPACT}}/10  
**Tickets:** {{TICKETS}}`,

    // Changes section
    changes: `### Changes
{{CHANGES}}`,

    // Ticket references section
    tickets: `### Related Tickets
{{TICKETS}}`,

    // Footer with metadata
    footer: `---
Generated by lazyPR | Size: {{SIZE}} | Impact: {{IMPACT}}`,
  },

  // Custom placeholder mappings
  placeholders: {
    TICKETS: "JIRA-123, #456, LINEAR-789",
    SIZE: "medium",
    IMPACT: "7",
    CHANGES: "- Added new authentication flow\n- Updated database schema\n- Fixed edge cases",
    AUTHOR: "developer",
    BRANCH: "feature/auth-flow",
  },

  // PR title enhancement rules
  titleRules: {
    // If PR is small and low impact
    smallLowImpact: "{{SIZE}} change: {{CHANGES}}",

    // If PR has breaking changes
    breakingChange: "BREAKING: {{CHANGES}}",

    // Default template
    default: "{{SIZE}}: {{CHANGES}} ({{TICKETS}})",
  },

  // Size thresholds
  sizeThresholds: {
    small: 50, // lines
    medium: 200, // lines
    large: 500, // lines
  },

  // Custom validators
  validators: {
    // Custom ticket patterns to detect
    ticketPatterns: [
      { pattern: "JIRA-[0-9]+", type: "JIRA" },
      { pattern: "#[0-9]+", type: "GitHub" },
      { pattern: "LINEAR-[A-Z]+-[0-9]+", type: "Linear" },
      { pattern: "PROJ-[0-9]+", type: "Project" },
    ],

    // Files to ignore
    ignoreFiles: [
      "package-lock.json",
      "yarn.lock",
      "*.md",
      "node_modules/**",
      ".env*",
      "dist/**",
      "build/**",
    ],
  },
};

export default featureConfig;
